((sum=0))
#for i in `echo THERAPEUTIC_OR_PREVENTIVE_PROCEDURE DRUG CHEMICAL_SUBSTANCE HAZARDOUS_OR_POISONOUS_SUBSTANCE ESTABLISHED_PHARMACOLOGIC_CLASS CHEMICAL_CLASS VITAMIN LAB_PROCEDURE SURGICAL_AND_MEDICAL_PROCEDURES DIAGNOSTIC_PROCEDURE LAB_TEST_COMPONENT STUDY DRUG_ADJECTIVE`
#for i in `echo DISEASE MENTAL_OR_BEHAVIORAL_DYSFUNCTION CONGENITAL_ABNORMALITY CELL_OR_MOLECULAR_DYSFUNCTION DISEASE_ADJECTIVE`
#for i in `echo  BODY_PART_OR_ORGAN_COMPONENT BODY_LOCATION_OR_REGION BODY_SUBSTANCE CELL CELL_LINE CELL_COMPONENT BIO_MOLECULE METABOLITE HORMONE BODY_ADJECTIVE`
#for i in `echo  PERSON PERSON_ADJECTIVE`
#for i in `echo  LOCATION LOCATION_ADJECTIVE`
#for i in `echo  LOCATION LOCATION_ADJECTIVE`
#for i in `echo BIO SPECIES BACTERIUM VIRUS BIO_ADJECTIVE`
for i in `echo PRODUCT MEDICAL_DEVICE DEVICE DEVICE_ADJECTIVE`
do
    grep "$i" bootstrap_entities.txt | wc -l
    x=`grep "$i" bootstrap_entities.txt | wc -l`
    ((sum=sum+x))

done
echo $sum
